name: "Spec Tests"

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:

env:
  HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
  HONEYCOMB_DATASET: litmus tests

jobs:
  Spec:
    name: "Spec Tests (Ruby: ${{matrix.ruby_version}})"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.5
          - 2.6
          - 2.7

    env:
      BUILDEVENT_FILE: '../buildevents.txt'
      RVM_GEM_VERSION: ${{ matrix.ruby_version }}

    steps:
      - run: |
          echo "SANITIZED_RUBY_VERSION=$(echo '${{ matrix.ruby_version }}' | sed 's/~> //g')" >> $GITHUB_ENV
      - run: |
          echo 'ruby_version=${{ env.SANITIZED_RUBY_VERSION }}' >> $BUILDEVENT_FILE
      - name: "Honeycomb: Start first step"
        run: |
          echo "STEP_ID=${{ env.SANITIZED_RUBY_VERSION }}-spec" >> $GITHUB_ENV
          echo STEP_START=$(date +%s) >> $GITHUB_ENV
      - name: "Honeycomb: Start recording"
        uses: puppetlabs/kvrhdn-gha-buildevents@pdk-templates-v1
        with:
          apikey: ${{ env.HONEYCOMB_WRITEKEY }}
          dataset: ${{ env.HONEYCOMB_DATASET }}
          job-status: ${{ job.status }}
          matrix-key: ${{ env.SANITIZED_RUBY_VERSION }}

      - name: Checkout Source
        uses: actions/checkout@v2

      - name: "Activate Ruby ${{ matrix.ruby_version }}"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true

      - name: Print bundle environment
        run: |
          echo ::group::bundler environment
          buildevents cmd $TRACE_ID $STEP_ID 'bundle env' -- bundle env
          echo ::endgroup::
      - name: Run Static & Syntax Tests
        run: |
          buildevents cmd $TRACE_ID $STEP_ID 'static_syntax_checks Ruby ${{ matrix.ruby_version }}' -- bundle exec rubocop
      
      - name: Run spec tests
        run: |
          buildevents cmd $TRACE_ID $STEP_ID 'rake spec Ruby ${{ matrix.ruby_version }}' -- bundle exec rake spec